---
layout: post
title: "pwntools安装"
pubtime: 2020-09-01
updatetime: 2020-09-01
categories: EnvironmentBuild
tags: pwntools
---

Ubuntu下pwntools安装，需要注意：[!] Pwntools does not support 32-bit Python.  Use a 64-bit release.

# pwntools安装

总共四行命令：

```
sudo apt-get install libffi-dev
sudo apt-get install libssl-dev
sudo apt-get install python
sudo apt-get install python-pip
pip install pwntools
```

*要真这么痛快就不记录了，差点以为学习之路死在工具安装*

## 1.1 E:Unable to locate package xxx

尝试`sudo apt-get update`

如果没有解决则可能

1. 被墙了——换成国内源即可

   ```
   sudo cp sources.list sources.list.bak
   sudo gedit sources.list
   ```

   在列表中添加

   ```
   deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial main restricted universe multiverse
   # deb-src https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial main restricted universe multiverse
   deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial-updates main restricted universe multiverse
   # deb-src https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial-updates main restricted universe multiverse
   deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial-backports main restricted universe multiverse
   # deb-src https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial-backports main restricted universe multiverse
   deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial-security main restricted universe multiverse
   # deb-src https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial-security main restricted universe multiverse
   ```

   更新源

   ```
   sudo apt-get update
   ```

2. architecture不兼容——删掉不兼容的architecture(没用到)

## 1.2 The following packages have unmet dependencies

依赖库安装版本不匹配。

错误信息示例：

```
The following packages have unmet dependencies:
 zlib1g-dev : Depends: zlib1g (= 1:1.2.8.dfsg-2ubuntu4.3) but 1:1.2.8.dfsg-2ubuntu5 is to be installed
E: Unable to correct problems, you have held broken packages.
```

指定版本号安装依赖，例如

```
sudo apt-get install zlib1g=1:1.2.8.dfsg-2ubuntu4.3
```

## 1.3 Python.h: No such file or directory

可以进入/usr/include/文件夹下的Pythonx.x文件夹里查找是否有Python.h这个文件。

如果是第一种情况，那么需要安装python-dev这个包

```sudo apt-get install python-dev
sudo apt-get install python-dev
```

## 1.4 多重依赖

```
sudo apt --fix-broken install
sudo apt-get update
sudo apt-get upgrade
```

*(然而我并没能解决自动下载依赖的问题，还是手动下载的)*

## 1.5 无法获得锁 /var/lib/dpkg/lock -open （11：资源暂时不可用）

在ubuntu系统的termial下，用apt-get install 安装软件的时候，如果在未完成下载的情况下将terminal close。此时 apt-get进程可能没有结束。结果，如果再次运行apt-get就会出这个错误。

可以用ps找出apt-get进程然后结束它，也可以强制解锁：

```
sudo rm /var/cache/apt/archives/lock
sudo rm /var/lib/dpkg/lock
```

